spring:
  profiles:
    active: dev


  #mybatis配置
mybatis:
  type-aliases-package: com.fruit.lou.dao.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #configLocation: classpath:/mybatis-config.xml


