spring:
  #数据源
  datasource:
    url: jdbc:mysql://localhost:3306/fruit?useUnicode=true&amp;characterEncoding=UTF-8
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver


  #mybatis配置
  mybatis:
    typeAliasesPackage: com.fruit.lou.dao.entity
    mapperLocations: classpath:mapper/*.xml
    #configLocation: classpath:/mybatis-config.xml


